# name: Release

# on:
#   push:
#     tags: 
#       - 'v*'

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
      
#     - name: Checkout
#       uses: actions/checkout@v3
#       with:
#         fetch-depth: 0

#     - name: Compile
#     - run: make

#     # automatic create a release
#     - name: Release
#       uses: softprops/action-gh-release@v1
#       with:
#         files: Release.txt
