name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [clang, gcc]

    name: ${{ matrix.os }} (${{ matrix.compiler }})

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Compile and install
      run: make install

    - name: Test printing shortcut version
      run: ./shortcut --version
      
    - name: Test printing shortcut list
      run: ./shortcut --list
      
    - name: Test printing shortcut page
      run: ./shortcut firefox
